# Generated by Django 5.2.6 on 2025-10-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الصورة')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='صورة الخلفية')),
                ('active', models.BooleanField(default=True, verbose_name='مفعلة')),
            ],
        ),
    ]
