# Generated by Django 5.2.6 on 2025-10-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='is_tager',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='user',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='account_type',
            field=models.CharField(choices=[('user', 'مستخدم'), ('vendor', 'تاجر')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginuser',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='username',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
    ]
