# Generated by Django 5.2.6 on 2025-10-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_delete_imagebackground_delete_loginuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('BuyingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Type', models.CharField(choices=[('Taking return', 'Taking return'), ('Not taking return', 'Not taking return')], max_length=20)),
            ],
        ),
    ]
