# Generated by Django 5.2.6 on 2025-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
